# Generated by Django 4.1.3 on 2022-11-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200, null=True)),
                ("last_name", models.CharField(max_length=200, null=True)),
                ("email", models.CharField(max_length=200, null=True)),
                ("password", models.CharField(max_length=255, null=True)),
                ("mobile", models.BigIntegerField()),
                ("gender", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
