# Generated by Django 4.1.3 on 2022-11-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flipkart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="catagory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("images", models.ImageField(upload_to="upload/catagory/")),
            ],
        ),
    ]
