# Generated by Django 4.1.3 on 2022-11-28 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flipkart", "0002_catagory"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pro_name", models.CharField(max_length=50, null=True)),
                ("price", models.IntegerField()),
                ("desc", models.TextField(max_length=200, null=True)),
                ("pro_image", models.ImageField(upload_to="upload/product/")),
                (
                    "catagory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flipkart.catagory",
                    ),
                ),
            ],
        ),
    ]
