# Generated by Django 4.1.3 on 2022-12-12 03:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flipkart", "0003_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order_dtls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=300, null=True)),
                ("mobile", models.BigIntegerField()),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                ("status", models.BooleanField(default=False)),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flipkart.registration",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flipkart.product",
                    ),
                ),
            ],
        ),
    ]
